# Generated by Django 5.2.17 on 2026-09-24 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="categories/"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Lucide icon name used by the frontend, e.g. 'smartphone'.",
                        max_length=40,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Show on the homepage category showcase.",
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="categories.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ("display_order", "name"),
            },
        ),
    ]
