# Generated by Django 5.2.17 on 2026-09-24 15:29

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=40, unique=True)),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage (%)"),
                            ("fixed", "Fixed amount (₦)"),
                        ],
                        default="percentage",
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "minimum_order",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "maximum_discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional cap for percentage coupons (₦).",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("expiry_date", models.DateTimeField(blank=True, null=True)),
                (
                    "usage_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Leave blank for unlimited uses.",
                        null=True,
                    ),
                ),
                ("times_used", models.PositiveIntegerField(default=0, editable=False)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
