# Generated by Django 5.2.17 on 2026-09-24 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("paystack", "Paystack"),
                            ("test", "Test mode (no real charge)"),
                        ],
                        default="paystack",
                        max_length=20,
                    ),
                ),
                ("reference", models.CharField(max_length=100, unique=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount in Naira, copied from the order total.",
                        max_digits=14,
                    ),
                ),
                ("currency", models.CharField(default="NGN", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initialized", "Initialized"),
                            ("success", "Successful"),
                            ("failed", "Failed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="initialized",
                        max_length=20,
                    ),
                ),
                ("authorization_url", models.URLField(blank=True, max_length=500)),
                ("gateway_response", models.CharField(blank=True, max_length=255)),
                ("channel", models.CharField(blank=True, max_length=40)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
