import {
  Activity,
  BatteryCharging,
  Briefcase,
  Cable,
  Camera,
  Cctv,
  Ear,
  Gamepad2,
  HardDrive,
  HardDriveDownload,
  Headphones,
  Headset,
  Keyboard,
  Laptop,
  MemoryStick,
  Monitor,
  Mouse,
  MousePointer2,
  Music,
  Network,
  PcCase,
  PlugZap,
  RadioTower,
  Router,
  ShieldCheck,
  Smartphone,
  Speaker,
  Tablet,
  Tag,
  Usb,
  Watch,
  Wifi,
  Zap,
} from 'lucide-react'

/** Maps the `icon` string stored on each Category (backend) to a Lucide icon. */
const ICONS = {
  smartphone: Smartphone,
  tablet: Tablet,
  laptop: Laptop,
  'pc-case': PcCase,
  monitor: Monitor,
  keyboard: Keyboard,
  mouse: Mouse,
  'mouse-pointer-2': MousePointer2,
  briefcase: Briefcase,
  'plug-zap': PlugZap,
  'battery-charging': BatteryCharging,
  cable: Cable,
  headset: Headset,
  ear: Ear,
  headphones: Headphones,
  speaker: Speaker,
  watch: Watch,
  activity: Activity,
  'memory-stick': MemoryStick,
  usb: Usb,
  'hard-drive': HardDrive,
  'hard-drive-download': HardDriveDownload,
  network: Network,
  router: Router,
  wifi: Wifi,
  'radio-tower': RadioTower,
  cctv: Cctv,
  'gamepad-2': Gamepad2,
  music: Music,
  'shield-check': ShieldCheck,
  zap: Zap,
  camera: Camera,
}

export function categoryIcon(name) {
  return ICONS[name] || Tag
}
